### PR TITLE
Add a configuration file

### LINKED ISSUE #11: vm: Console toggling should be configurable
The console is currently toggled via the `Grave` key (the key under Escape. That is the tilde `~` on English keyboards).

Non-English keyboards struggle using this as the key to toggle the Console and so it would be great if this was configurable for users.

I am keen to [use the app_dirs crate](https://crates.io/crates/app_dirs) when figuring out where we should store user configuration files. I am not too concerned with the format of the files, although I imagine JSON is probably the best approach.

### PR DESCRIPTION
**Pull request by seventh-chord**
Resolves #11.
Stores configuration in `config.json`, in whatever folder is appropriate for configuration files on the current platform (Using `app_dirs`). Currently, a default configuration file is created and stored, and then loaded on subsequent runs. The only way to change the configuration is by editing this config file. In the future this could be extended by an in-game menu.

### CODE REVIEW

**Comment by simon-whitehead** [comment]
This is all great! I do however think it should be completely encapsulated inside the `Console` itself and the levels shouldn't have to know where a configuration file is or how it is loaded. Are we able to move all of it into the `Console`?

**Comment by seventh-chord** [comment]
Moving it to console would require moving the code to turn the console on into `console.rs`, and updating the console regardless of whether it is open. Ill look into it, but I think it should work just fine.

**Comment by simon-whitehead** [comment]
I am wondering whether a `console.try_toggle(scancode, timestamp);` would be fine, which is called every time and encapsulates the rest of the logic? I guess thats what you meant by updating the console every time. I will leave it to you to decide what you think is best :)

**Comment by seventh-chord** [comment]
The way I now implemented it is by calling `console.process(...)` every frame, and then returning early from the function if the console is off. That way we do not have to add any functions, and all the logic for toggling the console is in one place.

**Comment by simon-whitehead** [comment]
This is fantastic @seventh-chord! Thank you so much! I tested this in a few ways. I changed the scancode to `84` in the config file to make it the forward-slash on my Keypad and sure enough, it all works as expected.

Thanks again for an amazing contribution! I will merge this now 😄

**Pull request merged**
