### PR TITLE
WIP: Custom Console

### PR DESCRIPTION
**Pull request by simon-whitehead**
This PR introduces a custom console that appears in-game.

[You can view a GIF of it in action here (2016-12-22) (1.2MB)](https://cloud.githubusercontent.com/assets/2499070/21414726/2650b464-c856-11e6-884f-c43a68d51c68.gif)

**This is a work in progress.**

Adding a custom console like this:

* Allows support for all platforms. Crates like Termion don't support Windows and since I personally work with Windows half of the time I would like to support Windows.
* Allows easier implementations of Ctrl+C functionality that works across environments.
* Easier/customizable history navigation.
* Sidesteps the "window must run via initiating thread" rule that both Windows and OSX have. That is half the reason theres a bit of a race condition in the current implementation where some commands complete _after_ the `hakka> ` leading text.
* Looks cooler - and its customizable.

Currently the console is triggered via the tilde/backtick key. It only accepts "exit" as a command for now.

### CODE REVIEW

**Comment by simon-whitehead** [comment]
Added the `shift` flag to check for the Shift keys being pressed when toggling the console. This was to fix the pipe `|` character causing the console to be hidden.

As a nice side effect.. the console now also accepts tilde `~` characters.. which also never used to work.

**Comment by daschfg** [comment]
Unfortunately, neither the backslash nor the backquote are currently working for me for toggling the console.
I would blame my german keyboard layout for it, where both are only available via a key combination (Shift for backquote and right Alt for backslash).
I got it working after I moved the call to toggle into the TextInput-event handling like this (for main.rs):
```rust
Event::TextInput { ref text, .. } => {
    if text == "`" || text == "\\" {
        vm.console.toggle();
    }
}
```
in both console.rs and main.rs.
I'm not very versed with SDL, is there anything speaking against calling it there, instead of during the KeyUp-event?

**Comment by simon-whitehead** [comment]
@daschfg I don't believe there are any potential issues moving it. I only put it in `KeyUp` because it seemed more appropriate at the time and it worked for me.

I've gone ahead and implemented your fix and its all working great. I will push this up now.

Thanks for the suggestion!

**Comment by seventh-chord** [comment]
@daschfg could you check if you can toggle the console with the new system? The grave key (Bellow escape, to the left of 1) is used to toggle the console

**Comment by daschfg** [comment]
Toggling the console now works for me, thank you.
However, there is still a minor issue with german keyboard layout with this solution.

Citing [Wikipedia](https://en.wikipedia.org/wiki/German_keyboard_layout):
> The accent keys ^, `, ´ are dead keys: press and release an accent key, then press a letter key to produce accented characters (ô, á, ù, etc.)

So after toggling the console with the first press of the grave key, the next letter tipped for the console gets that sign. For example writing `exit` becomes `êxit`.
As I said, I'm not versed with SDL, maybe there is a workaround for this. Alternatively, I know it is currently used for closing the application, but maybe the escape key could be used in addition to the grave key?

**Comment by simon-whitehead** [comment]
I am not opposed to having multiple keys or changing the key. What key would feel most natural to you both on your respective layouts if not the Grave key?

**Comment by simon-whitehead** [comment]
A quick Google search suggests this is a common issue for games in general.. not just SDL2 ones (where the game maps to the Grave key and different layouts have issues). I am unsure how to handle this scenario, honestly. Any suggestions from you both would be most welcome.

**Comment by daschfg** [comment]
> What key would feel most natural to you both on your respective layouts if not the Grave key?

Personally, I would prefer Escape or Tab. But using Tab could be useful for some possible future auto completion and Escape for some possible future menu.
The only other keys I would come up with are the function keys. I don't think they feel that natural, but (without knowing too much other keyboard layouts) would hope they should cause the least problems.

In addition to that, maybe we could make the toggle key customizable.

**Comment by simon-whitehead** [comment]
I am keen on making it customizable. I think for now it would be best to get this PR merged with the Grave key and start a new branch for a config file (which includes the console toggle key setting).

**Comment by seventh-chord** [comment]
I think making it configurable would be the best way to go, as anything else would be a compromise: While it might work great on some layouts it will not work on others. Using the grave key as a default would probably be the best, as it is (as far as I am aware) the norm in most games. Maybe we could do something to detect if the grave key is a dead key, and switch to another default key in that case.

Edit: After looking into it, it seems like there is no decent way of detecting if a key is a dead-key in sdl2

**Comment by simon-whitehead** [comment]
I agree making it configurable is best. This is a common problem among game developers it seems.

I will look to merge this PR in the next day or so with the grave key as the default. I just want to test it a little bit more first.

After its merged, I would be keen to open another PR with a configuration file that lets you customize the key that toggles the console.

**Comment by simon-whitehead** [comment]
I am going to merge this now, I am very happy with it.

Thank you so much @daschfg and @seventh-chord for your contributions to this branch. I am very grateful indeed! 😃

**Pull request merged**
